// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGDf8N5AXld79svrHNbm5WnmeJ3mIccms',
    appId: '1:683321627217:web:9f9fc23e6f5920580d9e70',
    messagingSenderId: '683321627217',
    projectId: 'whetherapp-874e6',
    authDomain: 'whetherapp-874e6.firebaseapp.com',
    storageBucket: 'whetherapp-874e6.firebasestorage.app',
    measurementId: 'G-T9J6VT1P6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo2zJkFaRRGljpVdj_b2Q_ix6PgpAXr-s',
    appId: '1:683321627217:android:15d6818d47fcc1290d9e70',
    messagingSenderId: '683321627217',
    projectId: 'whetherapp-874e6',
    storageBucket: 'whetherapp-874e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlhGTebXi47K0tjIYgos6p1MXC7oORCmM',
    appId: '1:683321627217:ios:0fccc67b2366d3020d9e70',
    messagingSenderId: '683321627217',
    projectId: 'whetherapp-874e6',
    storageBucket: 'whetherapp-874e6.firebasestorage.app',
    iosBundleId: 'com.example.whetherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlhGTebXi47K0tjIYgos6p1MXC7oORCmM',
    appId: '1:683321627217:ios:0fccc67b2366d3020d9e70',
    messagingSenderId: '683321627217',
    projectId: 'whetherapp-874e6',
    storageBucket: 'whetherapp-874e6.firebasestorage.app',
    iosBundleId: 'com.example.whetherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGDf8N5AXld79svrHNbm5WnmeJ3mIccms',
    appId: '1:683321627217:web:023a1a8d4e2706780d9e70',
    messagingSenderId: '683321627217',
    projectId: 'whetherapp-874e6',
    authDomain: 'whetherapp-874e6.firebaseapp.com',
    storageBucket: 'whetherapp-874e6.firebasestorage.app',
    measurementId: 'G-LLBVER05B9',
  );
}
